server:
  applicationConnectors:
    - type: http
      port: !!int ${HTTP_PLATFORM_PORT}

  adminConnectors:
    - type: http
      port: 9081  # Internal admin port

logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO

  appenders:
    - type: console

    - type: file
      # Dynamically pick log path from environment variable, fallback to ./logs
      currentLogFilename: /home/LogFiles/iservice.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /home/LogFiles/iservice-%d{yyyy-MM-dd}.%i.log
      archivedFileCount: 10
      maxFileSize: 100KB
      timeZone: UTC
